### ISSUE TITLE
No veo avances del proyecto

### ISSUE THREAD

**Issue by norman-ipn** [davidyesc/ProyectoED#5]
No hay avances del proyecto.
Si siguen interesados en que evalúe el proyecto, contensten todos este issue.
@davidyesc 
@Arthor666 
@JoseD19Ez 
@DavidToledoH

**Comment by JoseD19Ez** [comment]
> No hay avances del proyecto.
> Si siguen interesados ​​en evaluar el proyecto, contestar todos este tema.
> @davidyesc
> @ Arthor666
> @ JoseD19Ez
> @DavidToledoH

Seguimos interesados, aunque no hemos tenido gran avance sobre el proyecto, seguimos buscando opciones.

**Comment by DavidToledoH** [comment]
Estamos considerando más opciones ya que el proyecto que teniamos planeado es muy complejo para el corto tiempo que queda para la entrega.

**Comment by norman-ipn** [comment]
Definan el proyecto lo antes posible y me avisan cuando lo tengan.
